### ISSUE TITLE
signed dual volumes

### ISSUE THREAD

**Issue by lds2** [hirani/pydec#6]
Hi,

Does the Hodge operator calculation follow the signal convention defined in [1]?

1. Anil N. Hirani, Kaushik Kalyanaraman, and Evan B. VanderZee. Delaunay Hodge star. Computer-Aided Design, 45(2):540–544,2013.

Thanks.

**Comment by hirani** [comment]
On git repository, the “master" branch does not use this sign convention. But the “devel3” branch indeed does use this convention. The devel3 branch is a Python 3 port or PyDEC. It is not fully tested. Do you want to use Python 2 or Python 3?

Anil


On Oct 29, 2019, at 6:39 PM, Leon Denis da Silva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Does the Hodge operator calculation follow the signal convention defined in [1]?

  1.  Anil N. Hirani, Kaushik Kalyanaraman, and Evan B. VanderZee. Delaunay Hodge star. Computer-Aided Design, 45(2):540–544,2013.

Thanks.

**Comment by hirani** [comment]
Actually I just checked with my co-developer and indeed all branches on git implement the sign convention. Thus the branches “master”, “devel3” and “devel” all use signed Hodge star. You should use “master” for Python 2 and “devel3” for Python 3 version of PyDEC.

Anil


On Oct 29, 2019, at 7:09 PM, Anil N. Hirani <hirani@illinois.edu<mailto:hirani@illinois.edu>> wrote:

On git repository, the “master" branch does not use this sign convention. But the “devel3” branch indeed does use this convention. The devel3 branch is a Python 3 port or PyDEC. It is not fully tested. Do you want to use Python 2 or Python 3?

Anil


On Oct 29, 2019, at 6:39 PM, Leon Denis da Silva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Does the Hodge operator calculation follow the signal convention defined in [1]?

  1.  Anil N. Hirani, Kaushik Kalyanaraman, and Evan B. VanderZee. Delaunay Hodge star. Computer-Aided Design, 45(2):540–544,2013.

Thanks.

**Comment by lds2** [comment]
I'm using Python 2.

Initially, I intend to work on a non-Delaunay curved surface mesh. For example, Fig. 9 (see [2]). Does the git implantation work well for this case?

2. Mohamed, M. S., Hirani, A. N., & Samtaney, R. (2018). Numerical convergence of discrete exterior calculus on arbitrary surface meshes. International Journal for Computational Methods in Engineering Science and Mechanics, 19(3), 194-206.

Leon

**Comment by dialkforkaushik** [comment]
> I'm using Python 2.
> 
> Initially, I intend to work on a non-Delaunay curved surface mesh. For example, Fig. 9 (see [2]). Does the git implantation work well for this case?
> 
> 1. Mohamed, M. S., Hirani, A. N., & Samtaney, R. (2018). Numerical convergence of discrete exterior calculus on arbitrary surface meshes. International Journal for Computational Methods in Engineering Science and Mechanics, 19(3), 194-206.
> 
> Leon

HI Leon,

The issue you had raised a few months ago is resolved now. The sign conventions outlined in the paper had already been implemented but they have now been extended to work for any dimension complex embedded in (any appropriate) dimension. If you are still looking to use PyDEC, and you are on Python2, you should clone the Python2 branch. Thanks!

**Comment by dialkforkaushik** [comment]
Hi 

> I'm using Python 2.
> 
> Initially, I intend to work on a non-Delaunay curved surface mesh. For example, Fig. 9 (see [2]). Does the git implantation work well for this case?
> 
> 1. Mohamed, M. S., Hirani, A. N., & Samtaney, R. (2018). Numerical convergence of discrete exterior calculus on arbitrary surface meshes. International Journal for Computational Methods in Engineering Science and Mechanics, 19(3), 194-206.
> 
> Leon

Hi Leon,

The issue you had raised a few months is now resolved. The signed Hodge star computations had already been implemented in an earlier version of PyDEC. But the version now generalizes it for any dimension complex embedded in any (appropriate) dimension. If you need a Python2 compatible version, please clone the Python2 branch. The master branch PyDEC is for Python3. Thanks!
